apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gammapvc
  namespace: space
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: gamma-pv

