apiVersion: v1
kind: PersistentVolume
metadata:
  name: gamma-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-storage
  nfs:
    server: 192.168.50.254
    path: /exports-ocp4
