apiVersion: config.openshift.io/v1
kind: Project
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2023-09-28T14:08:47Z"
  generation: 2
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 72d0e456-95f1-4410-926d-04980c8ba544
  resourceVersion: "999342"
  uid: 0694806e-02b5-4cf5-9d6e-2905e41e60f7
spec:
  projectRequestTemplate:
    name: project-request
